### ISSUE TITLE
Any chance of a hex release?

### ISSUE THREAD

**Issue by trinode** [sorentwo/flippant#2]
I've been banging my head on the table trying to work out how to get the current rule state out of flippant so they can be displayed on a frontend, turns out I needed the unreleased breakdown/0 if you could release 0.3 that would be awesome, then we don't have to point directly to the git repo :)

**Comment by sorentwo** [comment]
Hex release made! Thanks for asking, it's great to know people are using it. For what its worth, I've been working on a frontend plug component but haven't had much time lately. I'd be curious to see what you/your team come up with, if you're willing to share.

https://hexdocs.pm/flippant/0.3.0
